name: saltstack-file-formula
source: https://github.com/bechtoldt/saltstack-file-formula
summary: SaltStack Formula to manage resources like filesystems, quota and more
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
